global:
  scrape_interval: 15s
  evaluation_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

rule_files:
  - "alerting_rules.yml"

scrape_configs:
  - job_name: 'fastapi_app'
    static_configs:
      - targets: ['localhost:8000']    # ← CHANGÉ !
    metrics_path: '/metrics'
    scrape_interval: 10s